"""AST parsing utilities"""

from .parser import (
    ASTParser,
    CFamilyParser,
    ParseResult,
    ASTNode,
    Language,
    parse_code,
)
from .utils import (
    get_node_by_line,
    get_nodes_in_range,
    find_nodes_by_type,
    get_function_nodes,
    get_control_flow_nodes,
    map_vul_lines_to_nodes,
    get_smallest_nodes_for_lines,
    get_parent_chain,
    get_containing_function,
    serialize_ast,
    deserialize_ast,
    get_function_calls,
    get_identifiers,
    ast_to_dict,
    get_node_text_from_source,
    count_node_types,
    get_leaf_nodes,
    get_depth,
    get_max_depth,
)

__all__ = [
    # Parser classes
    "ASTParser",
    "CFamilyParser",
    "ParseResult",
    "ASTNode",
    "Language",
    "parse_code",
    # Utility functions
    "get_node_by_line",
    "get_nodes_in_range",
    "find_nodes_by_type",
    "get_function_nodes",
    "get_control_flow_nodes",
    "map_vul_lines_to_nodes",
    "get_smallest_nodes_for_lines",
    "get_parent_chain",
    "get_containing_function",
    "serialize_ast",
    "deserialize_ast",
    "get_function_calls",
    "get_identifiers",
    "ast_to_dict",
    "get_node_text_from_source",
    "count_node_types",
    "get_leaf_nodes",
    "get_depth",
    "get_max_depth",
]
